// JavaCup specification for a simple expression evaluator (w/ actions)

namespace TypeCobol.Compiler.CupParser;

using TUVienna.CS_CUP.Runtime;
using System;
using System.Collections;
using System.Collections.Generic;
using TypeCobol.Compiler.CodeElements;
using TypeCobol.Compiler.CupParser.NodeBuilder;

action code {:
	//Current program identification
	TypeCobol.Compiler.CodeElements.ProgramIdentification programIdentification;
	//Curerent library copy;
	TypeCobol.Compiler.CodeElements.LibraryCopyCodeElement libraryCopy;
:};

parser code {:
	// The Program Class Builder instance.
	public IProgramClassBuilder Builder
	{
		get;
		set;
	}
	// The Error Reporter instance
	public ICupParserErrorReporter ErrorReporter
	{
		get;
		set;
	}

  // get the current state of the parser.
  public int getParserState() 
  {
	return ((Symbol)stack.Peek()).parse_state;	
  }

  public override void report_fatal_error(
    string   message, 
    object   info)
	{
		if(ErrorReporter != null) {
			if (ErrorReporter.ReportFatalError(this, message, info))
			{
				return;
			}
		}
		base.report_fatal_error(message, info);
	}

	public override void report_error(string message, object info)
	{
		if(ErrorReporter != null) {
			if (ErrorReporter.ReportError(this, message, info))
			{
				return;
			}
		}
		base.report_error(message, info);
	}

	public override void syntax_error(Symbol cur_token)
	{
		if(ErrorReporter != null) {
			if (ErrorReporter.SyntaxError(this, cur_token))
			{
				return;
			}
		}
		base.syntax_error(cur_token);
	}

	public override void unrecovered_syntax_error(Symbol cur_token)
	{
		if(ErrorReporter != null) {
			if (ErrorReporter.UnrecoveredSyntaxError(this, cur_token))
			{
				return;
			}
		}
		base.unrecovered_syntax_error(cur_token);
	}
:};


/* Terminals (tokens returned by the scanner). */
terminal TypeCobol.Compiler.CodeElements.ProgramIdentification ProgramIdentification;
terminal TypeCobol.Compiler.CodeElements.ProgramEnd ProgramEnd;
terminal TypeCobol.Compiler.CodeElements.ClassIdentification ClassIdentification;
terminal TypeCobol.Compiler.CodeElements.ClassEnd ClassEnd;
terminal TypeCobol.Compiler.CodeElements.FactoryIdentification FactoryIdentification;
terminal TypeCobol.Compiler.CodeElements.FactoryEnd FactoryEnd;
terminal TypeCobol.Compiler.CodeElements.ObjectIdentification ObjectIdentification;
terminal TypeCobol.Compiler.CodeElements.ObjectEnd ObjectEnd;
terminal TypeCobol.Compiler.CodeElements.MethodIdentification MethodIdentification;
terminal TypeCobol.Compiler.CodeElements.MethodEnd MethodEnd;
terminal TypeCobol.Compiler.CodeElements.EnvironmentDivisionHeader EnvironmentDivisionHeader;
terminal TypeCobol.Compiler.CodeElements.DataDivisionHeader DataDivisionHeader;
terminal TypeCobol.Compiler.CodeElements.ProcedureDivisionHeader ProcedureDivisionHeader;
terminal TypeCobol.Compiler.CodeElements.DeclarativesHeader DeclarativesHeader;
terminal TypeCobol.Compiler.CodeElements.DeclarativesEnd DeclarativesEnd;
terminal TypeCobol.Compiler.CodeElements.SectionHeader SectionHeader;
terminal TypeCobol.Compiler.CodeElements.ConfigurationSectionHeader ConfigurationSectionHeader;
terminal TypeCobol.Compiler.CodeElements.InputOutputSectionHeader InputOutputSectionHeader;
terminal TypeCobol.Compiler.CodeElements.FileSectionHeader FileSectionHeader;
terminal TypeCobol.Compiler.CodeElements.WorkingStorageSectionHeader WorkingStorageSectionHeader;
terminal TypeCobol.Compiler.CodeElements.LocalStorageSectionHeader LocalStorageSectionHeader;
terminal TypeCobol.Compiler.CodeElements.LinkageSectionHeader LinkageSectionHeader;
terminal TypeCobol.Compiler.CodeElements.ParagraphHeader ParagraphHeader;
terminal TypeCobol.Compiler.CodeElements.FileControlParagraphHeader FileControlParagraphHeader;
terminal TypeCobol.Compiler.CodeElements.IOControlParagraphHeader IOControlParagraphHeader;
terminal TypeCobol.Compiler.CodeElements.SentenceEnd SentenceEnd;
terminal TypeCobol.Compiler.CodeElements.FileDescriptionEntry FileDescriptionEntry;
terminal TypeCobol.Compiler.CodeElements.DataDescriptionEntry DataDescriptionEntry;
terminal TypeCobol.Compiler.CodeElements.DataRedefinesEntry DataRedefinesEntry;
terminal TypeCobol.Compiler.CodeElements.DataRenamesEntry DataRenamesEntry;
terminal TypeCobol.Compiler.CodeElements.DataConditionEntry DataConditionEntry;
terminal TypeCobol.Compiler.CodeElements.FileControlEntry FileControlEntry;
terminal TypeCobol.Compiler.CodeElements.IOControlEntry IOControlEntry;
terminal TypeCobol.Compiler.CodeElements.SourceComputerParagraph SourceComputerParagraph;
terminal TypeCobol.Compiler.CodeElements.ObjectComputerParagraph ObjectComputerParagraph;
terminal TypeCobol.Compiler.CodeElements.SpecialNamesParagraph SpecialNamesParagraph;
terminal TypeCobol.Compiler.CodeElements.RepositoryParagraph RepositoryParagraph;
terminal TypeCobol.Compiler.CodeElements.AcceptStatement AcceptStatement;
terminal TypeCobol.Compiler.CodeElements.AddStatement AddStatement;
terminal TypeCobol.Compiler.CodeElements.AlterStatement AlterStatement;
terminal TypeCobol.Compiler.CodeElements.CallStatement CallStatement;
terminal TypeCobol.Compiler.CodeElements.CancelStatement CancelStatement;
terminal TypeCobol.Compiler.CodeElements.CloseStatement CloseStatement;
terminal TypeCobol.Compiler.CodeElements.ComputeStatement ComputeStatement;
terminal TypeCobol.Compiler.CodeElements.ContinueStatement ContinueStatement;
terminal TypeCobol.Compiler.CodeElements.DeleteStatement DeleteStatement;
terminal TypeCobol.Compiler.CodeElements.DisplayStatement DisplayStatement;
terminal TypeCobol.Compiler.CodeElements.DivideStatement DivideStatement;
terminal TypeCobol.Compiler.CodeElements.EntryStatement EntryStatement;
terminal TypeCobol.Compiler.CodeElements.EvaluateStatement EvaluateStatement;
terminal TypeCobol.Compiler.CodeElements.ExecStatement ExecStatement;
terminal TypeCobol.Compiler.CodeElements.ExitMethodStatement ExitMethodStatement;
terminal TypeCobol.Compiler.CodeElements.ExitProgramStatement ExitProgramStatement;
terminal TypeCobol.Compiler.CodeElements.ExitStatement ExitStatement;
terminal TypeCobol.Compiler.CodeElements.GobackStatement GobackStatement;
terminal TypeCobol.Compiler.CodeElements.GotoStatement GotoStatement;
terminal TypeCobol.Compiler.CodeElements.IfStatement IfStatement;
terminal TypeCobol.Compiler.CodeElements.InitializeStatement InitializeStatement;
terminal TypeCobol.Compiler.CodeElements.InspectStatement InspectStatement;
terminal TypeCobol.Compiler.CodeElements.InvokeStatement InvokeStatement;
terminal TypeCobol.Compiler.CodeElements.MergeStatement MergeStatement;
terminal TypeCobol.Compiler.CodeElements.MoveStatement MoveStatement;
terminal TypeCobol.Compiler.CodeElements.MultiplyStatement MultiplyStatement;
terminal TypeCobol.Compiler.CodeElements.NextSentenceStatement NextSentenceStatement;
terminal TypeCobol.Compiler.CodeElements.OpenStatement OpenStatement;
terminal TypeCobol.Compiler.CodeElements.PerformProcedureStatement PerformProcedureStatement;
terminal TypeCobol.Compiler.CodeElements.PerformStatement PerformStatement;
terminal TypeCobol.Compiler.CodeElements.ReadStatement ReadStatement;
terminal TypeCobol.Compiler.CodeElements.ReleaseStatement ReleaseStatement;
terminal TypeCobol.Compiler.CodeElements.ReturnStatement ReturnStatement;
terminal TypeCobol.Compiler.CodeElements.RewriteStatement RewriteStatement;
terminal TypeCobol.Compiler.CodeElements.SearchStatement SearchStatement;
terminal TypeCobol.Compiler.CodeElements.SetStatement SetStatement;
terminal TypeCobol.Compiler.CodeElements.SortStatement SortStatement;
terminal TypeCobol.Compiler.CodeElements.StartStatement StartStatement;
terminal TypeCobol.Compiler.CodeElements.StopStatement StopStatement;
terminal TypeCobol.Compiler.CodeElements.StringStatement StringStatement;
terminal TypeCobol.Compiler.CodeElements.SubtractStatement SubtractStatement;
terminal TypeCobol.Compiler.CodeElements.UnstringStatement UnstringStatement;
terminal TypeCobol.Compiler.CodeElements.UseStatement UseStatement;
terminal TypeCobol.Compiler.CodeElements.WriteStatement WriteStatement;
terminal TypeCobol.Compiler.CodeElements.XmlGenerateStatement XmlGenerateStatement;
terminal TypeCobol.Compiler.CodeElements.XmlParseStatement XmlParseStatement;
terminal TypeCobol.Compiler.CodeElements.AtEndCondition AtEndCondition;
terminal TypeCobol.Compiler.CodeElements.NotAtEndCondition NotAtEndCondition;
terminal TypeCobol.Compiler.CodeElements.AtEndOfPageCondition AtEndOfPageCondition;
terminal TypeCobol.Compiler.CodeElements.NotAtEndOfPageCondition NotAtEndOfPageCondition;
terminal TypeCobol.Compiler.CodeElements.OnExceptionCondition OnExceptionCondition;
terminal TypeCobol.Compiler.CodeElements.NotOnExceptionCondition NotOnExceptionCondition;
terminal TypeCobol.Compiler.CodeElements.OnOverflowCondition OnOverflowCondition;
terminal TypeCobol.Compiler.CodeElements.NotOnOverflowCondition NotOnOverflowCondition;
terminal TypeCobol.Compiler.CodeElements.InvalidKeyCondition InvalidKeyCondition;
terminal TypeCobol.Compiler.CodeElements.NotInvalidKeyCondition NotInvalidKeyCondition;
terminal TypeCobol.Compiler.CodeElements.OnSizeErrorCondition OnSizeErrorCondition;
terminal TypeCobol.Compiler.CodeElements.NotOnSizeErrorCondition NotOnSizeErrorCondition;
terminal TypeCobol.Compiler.CodeElements.ElseCondition ElseCondition;
terminal TypeCobol.Compiler.CodeElements.WhenCondition WhenCondition;
terminal TypeCobol.Compiler.CodeElements.WhenOtherCondition WhenOtherCondition;
terminal TypeCobol.Compiler.CodeElements.WhenSearchCondition WhenSearchCondition;
terminal TypeCobol.Compiler.CodeElements.AddStatementEnd AddStatementEnd;
terminal TypeCobol.Compiler.CodeElements.CallStatementEnd CallStatementEnd;
terminal TypeCobol.Compiler.CodeElements.ComputeStatementEnd ComputeStatementEnd;
terminal TypeCobol.Compiler.CodeElements.DeleteStatementEnd DeleteStatementEnd;
terminal TypeCobol.Compiler.CodeElements.DivideStatementEnd DivideStatementEnd;
terminal TypeCobol.Compiler.CodeElements.EvaluateStatementEnd EvaluateStatementEnd;
terminal TypeCobol.Compiler.CodeElements.IfStatementEnd IfStatementEnd;
terminal TypeCobol.Compiler.CodeElements.InvokeStatementEnd InvokeStatementEnd;
terminal TypeCobol.Compiler.CodeElements.MultiplyStatementEnd MultiplyStatementEnd;
terminal TypeCobol.Compiler.CodeElements.PerformStatementEnd PerformStatementEnd;
terminal TypeCobol.Compiler.CodeElements.ReadStatementEnd ReadStatementEnd;
terminal TypeCobol.Compiler.CodeElements.ReturnStatementEnd ReturnStatementEnd;
terminal TypeCobol.Compiler.CodeElements.RewriteStatementEnd RewriteStatementEnd;
terminal TypeCobol.Compiler.CodeElements.SearchStatementEnd SearchStatementEnd;
terminal TypeCobol.Compiler.CodeElements.StartStatementEnd StartStatementEnd;
terminal TypeCobol.Compiler.CodeElements.StringStatementEnd StringStatementEnd;
terminal TypeCobol.Compiler.CodeElements.SubtractStatementEnd SubtractStatementEnd;
terminal TypeCobol.Compiler.CodeElements.UnstringStatementEnd UnstringStatementEnd;
terminal TypeCobol.Compiler.CodeElements.WriteStatementEnd WriteStatementEnd;
terminal TypeCobol.Compiler.CodeElements.XmlStatementEnd XmlStatementEnd;
terminal TypeCobol.Compiler.CodeElements.LibraryCopyCodeElement LibraryCopy;
terminal TypeCobol.Compiler.CodeElements.FunctionDeclarationHeader FunctionDeclarationHeader;
terminal TypeCobol.Compiler.CodeElements.FunctionDeclarationEnd FunctionDeclarationEnd;
terminal TypeCobol.Compiler.CodeElements.ProcedureStyleCallStatement ProcedureStyleCall;
terminal TypeCobol.Compiler.CodeElements.Program Program;

/* Non terminals */
non terminal compilationUnit, cobolCompilationUnit;
non terminal cobolProgram, cobolClass, cobolProgramBase, nestedProgram;
non terminal classEndOpt;
non terminal factoryIdentificationOpt;
non terminal factoryIdentification;
non terminal factoryEndOpt;
non terminal factoryDataDivisionOpt;
non terminal factoryDataDivision;
non terminal factoryObjectprocedureDivisionOpt;
non terminal factoryObjectprocedureDivision;
non terminal objectIdentificationOpt;
non terminal objectIdentification;
non terminal objectEndOpt;
non terminal methodDefitionsOpt;
non terminal methodDefitions;
non terminal methodDefition;
non terminal methodEnvironmentDivisionOpt;
non terminal methodEnvironmentDivision;

non terminal programAttributes;
non terminal TypeCobol.Compiler.CodeElements.LibraryCopyCodeElement libraryCopyOpt;
non terminal TypeCobol.Compiler.CodeElements.ProgramEnd programEndOpt;
non terminal nestedProgramOpt;

non terminal TypeCobol.Compiler.CodeElements.EnvironmentDivisionHeader environmentDivisionOpt, environmentDivision;
non terminal configurationSectionOpt, configurationSection;
non terminal inputOutputSectionOpt, inputOutputSection;
non terminal configurationParagraphs;
non terminal configurationParagraph;
non terminal fileControlParagraphOpt, fileControlParagraph;
non terminal fileControlEntriesOpt, fileControlEntries;
non terminal ioControlParagraphOpt, ioControlParagraph, ioControlSentencesOpt;
non terminal ioControlEntries;

non terminal dataDefinitionEntry;
non terminal dataDefinitionEntries, dataDefinitionEntriesOpt;
non terminal execSqlStatement;
non terminal storageEntry;
non terminal storageEntries;
non terminal fileDescriptionEntry;
non terminal fileDescriptionEntriesOpt;
non terminal fileDescriptionEntries;
non terminal fileSection;
non terminal workingStorageSection;
non terminal localStorageSection;
non terminal linkageSection;
non terminal dataDivisionOpt, dataDivision;

non terminal procedureDivision, procedureDivisionOpt;
non terminal TypeCobol.Compiler.Nodes.Node statement, singleStatement, compoundStatement;
non terminal statements;
non terminal sentence;
non terminal sentences, sentencesOpt;
non terminal paragraph;
non terminal paragraphs;
non terminal section;
non terminal sections, declarativesSections;
non terminal declarativesSection;
non terminal declaratives, declarativesOpt;
non terminal functionDeclaration;
non terminal functionProcedureDivision, functionProcedureDivisionOpt;
non terminal functionOrSectionDeclaration;
non terminal functionOrSectionDeclarations;
non terminal configurationSectionHeader;

non terminal onAtEnd, noAtEnd;
non terminal endConditions;
non terminal onException, noException;
non terminal exceptionConditions;
non terminal onInvalidKey, noInvalidKey;
non terminal keyConditions;
non terminal onOverflow, noOverflow;
non terminal overflowConditions;
non terminal onSizeError, noSizeError;
non terminal sizeErrorConditions;

non terminal addStatementConditional;
non terminal callStatementConditions;
non terminal callStatementConditional;
non terminal computeStatementConditional;
non terminal deleteStatementConditional;
non terminal divideStatementConditional;
non terminal whenConditionClause;
non terminal whenConditionClauses;
non terminal whenSearchConditionClauses;
non terminal whenOtherClause;
non terminal whenSearchConditionClause;
non terminal TypeCobol.Compiler.CodeElements.CodeElement whenEvaluateCondition;
non terminal TypeCobol.Compiler.CupParser.NodeBuilder.CodeElementList whenEvaluateConditions;
non terminal evaluateStatementWithBody;
non terminal ifStatementWithBody;
non terminal invokeStatementConditional;
non terminal multiplyStatementConditional;
non terminal performStatementWithBody;
non terminal readStatementConditional;
non terminal rwStatementCondition;
non terminal rwStatementConditions;
non terminal returnStatementConditional;
non terminal rewriteStatementConditional;
non terminal startStatementConditional;
non terminal stringStatementConditional;
non terminal subtractStatementConditional;
non terminal unstringStatementConditional;
non terminal searchStatementWithBody;
non terminal writeStatementConditional;
non terminal xmlGenerateStatementConditional;
non terminal xmlParseStatementConditional;

non terminal procedureDivisionHeader;
non terminal functionProcedureDivisionHeader;
non terminal sectionHeader;
non terminal paragraphHeader;

non terminal ifstatement;
non terminal elseCondition;
non terminal nextSentenceStatement;
non terminal addStatement;
non terminal callStatement;
non terminal computeStatement;
non terminal deleteStatement;
non terminal divideStatement;
non terminal evaluateStatement;
non terminal invokeStatement;
non terminal multiplyStatement;
non terminal performStatement;
non terminal readStatement;
non terminal returnStatement;
non terminal rewriteStatement;
non terminal searchStatement;
non terminal whenSearchCondition;
non terminal whenEvaluateConditionsStart;
non terminal whenOtherCondition;
non terminal startStatement;
non terminal stringStatement;
non terminal subtractStatement;
non terminal unstringStatement;
non terminal writeStatement;
non terminal xmlGenerateStatement;
non terminal xmlParseStatement;

non terminal atEndCondition;
non terminal notAtEndCondition;
non terminal onExceptionCondition;
non terminal notOnExceptionCondition;
non terminal invalidKeyCondition;
non terminal notInvalidKeyCondition;
non terminal onOverflowCondition;
non terminal notOnOverflowCondition;
non terminal onSizeErrorCondition;
non terminal notOnSizeErrorCondition;

start with compilationUnit;

compilationUnit ::= {: my_parser.Builder.StartCobolCompilationUnit(); :} cobolCompilationUnit:cblCompUnit
	| {: my_parser.Builder.StartCobolCompilationUnit(); :} /*empty*/
	;

/* The grammar */
cobolCompilationUnit ::= cobolProgram:cp
	{:  :}
	|  cobolClass:cc
	{:  :}
	|  cobolCompilationUnit:ccu cobolProgram:cp
	{:  :}
	|  cobolCompilationUnit:ccu cobolClass:cc
	{:  :}
	;

/*
// --- TypeCobol PROGRAM ---
*/

cobolProgram ::=
	cobolProgramBase:cpb
    nestedProgramOpt:nsp
	programEndOpt:pe
	{: my_parser.Builder.EndCobolProgram(pe); :}
	;

cobolProgramBase ::=
	programAttributes:pas
	{: my_parser.Builder.StartCobolProgram(programIdentification, libraryCopy); :}
	environmentDivisionOpt:ed
	dataDivisionOpt:dv
	procedureDivisionOpt:pdiv
	{:  :}
	;

cobolClass ::= 
	ClassIdentification:ci
	EnvironmentDivisionHeader:edh
	factoryIdentificationOpt:fi
	objectIdentificationOpt:oi
	classEndOpt:ce
	{: :}
	;

classEndOpt ::= /*Empty*/
		{: :}
	|	ClassEnd:ce
		{: :}
		;

factoryIdentificationOpt ::= /*empty*/
		{: :}
	| factoryIdentification:fi
		{: :}
	;

factoryIdentification ::= FactoryIdentification:fi factoryDataDivisionOpt:fdd factoryObjectprocedureDivisionOpt:pdd factoryEndOpt:fe
		{: :}
	;

factoryEndOpt ::= /*empty*/
	{: :}
	| FactoryEnd:fe
	{: :}
	;
		
factoryDataDivisionOpt ::= /*empty*/
		{: :}
	|	factoryDataDivision:fdd
		{: :}
	;	

factoryDataDivision ::= DataDivisionHeader:ddh workingStorageSection:ws factoryObjectprocedureDivisionOpt:pdd
		{: :}
	;	

factoryObjectprocedureDivisionOpt ::= /*empty*/
		{: :}
	|	factoryObjectprocedureDivision:pdd
		{: :}
	;	

factoryObjectprocedureDivision ::= ProcedureDivisionHeader:pdh methodDefitionsOpt:mdefs
		{: :}
	;	

objectIdentificationOpt ::= /*empty*/
		{: :}
	|	objectIdentification:oi
		{: :}
	;	

objectIdentification ::= ObjectIdentification:oi workingStorageSection:ws factoryObjectprocedureDivisionOpt:pdd objectEndOpt:oe
		{: :}
	;	

objectEndOpt ::= /* empty */
		{: :}
	| ObjectEnd:oe
		{: :}
	;

methodDefitionsOpt ::= /* empty */
		{: :}
	|	methodDefitions:mdefs
		{: :}
	;	

methodDefitions ::= methodDefition:md
		{: :}
	| methodDefitions:mdefs methodDefition:md
		{: :}
	;

methodDefition ::= MethodIdentification:mi methodEnvironmentDivisionOpt:med dataDivisionOpt:dv procedureDivisionOpt:pdiv MethodEnd:me
	{: :}
	;

methodEnvironmentDivisionOpt ::= /*empty*/
	{:  :}
	| methodEnvironmentDivision:ed
	{:  :}
	;

methodEnvironmentDivision ::=
	EnvironmentDivisionHeader:edh  
	inputOutputSectionOpt:ioc
	{:  :}
	;

// TCRFUN_LIBRARY_COPY
programAttributes ::= ProgramIdentification:pid libraryCopyOpt:lc
	{:  programIdentification = pid; libraryCopy = lc; :}
	;

libraryCopyOpt ::= /*empty */
	{:  RESULT = null; :}
	| LibraryCopy:lc
	{:  RESULT = lc; :}
	;

programEndOpt ::= /* empty */
	| ProgramEnd:pe
	{:  RESULT = pe; :}
	;

nestedProgram ::= 	
	cobolProgramBase:cpb
    nestedProgramOpt:nsp
	ProgramEnd:pe
	{: my_parser.Builder.EndCobolProgram(pe); :}
	;

nestedProgramOpt ::= /* Empty */
	{:  :}
	| nestedProgramOpt:nsp nestedProgram:np
	{:  :}
	;

/*
// --- ENVIRONMENT DIVISION ---
*/

environmentDivisionOpt ::= /*empty*/
	{:  :}
	| environmentDivision:ed
	{:  :}
	;

environmentDivision ::=
	EnvironmentDivisionHeader:edh  
	{: my_parser.Builder.StartEnvironmentDivision(edh); :}
	configurationSectionOpt:cs
	inputOutputSectionOpt:ioc
	{: my_parser.Builder.EndEnvironmentDivision(); :}
	;

configurationSectionOpt ::= /*empty*/
	{:  :}
	| configurationSection:cs
	{:  :}
	;

configurationSection ::= configurationSectionHeader 
	{: my_parser.Builder.EndConfigurationSection(); :}
	| configurationSectionHeader
	  configurationParagraphs:cps
	{: my_parser.Builder.EndConfigurationSection(); :}
	;

configurationSectionHeader ::= ConfigurationSectionHeader:csh
	{: my_parser.Builder.StartConfigurationSection(csh); :}
	;

configurationParagraphs ::= configurationParagraph:cp
		{:  :}
	| configurationParagraphs configurationParagraph:cp
		{:  :}
	;

configurationParagraph ::= 
      SourceComputerParagraph:scp
	{: my_parser.Builder.StartSourceComputerParagraph(scp); my_parser.Builder.EndSourceComputerParagraph(); :}
	| ObjectComputerParagraph:ocp
	{: my_parser.Builder.StartObjectComputerParagraph(ocp); my_parser.Builder.EndObjectComputerParagraph(); :}
	| SpecialNamesParagraph:snp
	{: my_parser.Builder.StartSpecialNamesParagraph(snp); my_parser.Builder.EndSpecialNamesParagraph(); :}
	| RepositoryParagraph:rp
	{: my_parser.Builder.StartRepositoryParagraph(rp); my_parser.Builder.EndRepositoryParagraph(); :}
	;

inputOutputSectionOpt ::= /*empty*/
	{:  :}
	| inputOutputSection:ios
	{:  :}
	;

inputOutputSection ::= 
	InputOutputSectionHeader:iosh
	{: my_parser.Builder.StartInputOutputSection(iosh); :}
	fileControlParagraphOpt:fcp
	ioControlParagraphOpt:iocp
	{: my_parser.Builder.EndInputOutputSection(); :}
	;

fileControlParagraphOpt ::= /*empty*/
	{:  :}
	| fileControlParagraph:fcp
	{:  :}
	;

fileControlParagraph ::=
	FileControlParagraphHeader:fcph
	{: my_parser.Builder.StartFileControlParagraph(fcph); :}
	fileControlEntriesOpt:fces
	{: my_parser.Builder.EndFileControlParagraph(); :}
	;

fileControlEntriesOpt ::= /*empty*/
		{:  :}
	| fileControlEntries:fces
		{:  :}
	;

fileControlEntries ::= FileControlEntry:fce
		{: my_parser.Builder.StartFileControlEntry(fce); my_parser.Builder.EndFileControlEntry(); :}
	| fileControlEntries:fces FileControlEntry:fce
		{: my_parser.Builder.StartFileControlEntry(fce); my_parser.Builder.EndFileControlEntry(); :}
	;

ioControlParagraphOpt ::= /*empty*/
		{:  :}
	| ioControlParagraph:iocp
		{:  :}
	;

ioControlParagraph ::= 
	IOControlParagraphHeader:iocph
	ioControlSentencesOpt:iocs
	{:  :}
	;

ioControlSentencesOpt ::= /* empty */	
		{:  :}
	| ioControlEntries:ioces SentenceEnd:se
		{:	:}
	;

ioControlEntries ::= IOControlEntry:ioce
		{:  :}
	| ioControlEntries:ioces IOControlEntry:ioce
		{:  :}
	;


/*
// --- DATA DIVISION ---
*/
dataDivisionOpt ::= /*empty*/
	{:  :}
	| dataDivision:dv
	{:  :}
	;

dataDivision ::=
	DataDivisionHeader:ddh
	{: my_parser.Builder.StartDataDivision(ddh); :}
	fileSection:fs
	workingStorageSection :wss
	localStorageSection:lss
	linkageSection:ls
	{: my_parser.Builder.EndDataDivision(); :}
//|	error FileSectionHeader
//|	error WorkingStorageSectionHeader
//|	error LocalStorageSectionHeader
//|	error LinkageSectionHeader
	;

fileSection ::= /*empty*/
	{:  :}
	| FileSectionHeader:feh 
	{: my_parser.Builder.StartFileSection(feh); :}
	fileDescriptionEntriesOpt:des
	{: my_parser.Builder.EndFileSection(); :}
	| error {: my_parser.Builder.EndFileDescriptionEntryIfAny(); :} fileDescriptionEntries
	{: my_parser.Builder.EndFileSection(); :}
	;

fileDescriptionEntriesOpt ::= /*empty*/
	{:  :}
	| fileDescriptionEntries:fdes
	{:  :}
	;

fileDescriptionEntries ::=
	fileDescriptionEntry:fde
	{:  :}
	| fileDescriptionEntries:fdes fileDescriptionEntry:fde
	{:  :}
	;

fileDescriptionEntry ::= 
	FileDescriptionEntry:fde 
	{: my_parser.Builder.StartFileDescriptionEntry(fde); :}
	dataDefinitionEntries:dfes
	{: my_parser.Builder.EndFileDescriptionEntry(); :}
	;

workingStorageSection ::= /*empty*/
	{:  :}
	| WorkingStorageSectionHeader:wssh 
	{: my_parser.Builder.StartWorkingStorageSection(wssh); :}
	  storageEntries:ses
	{: my_parser.Builder.EndWorkingStorageSection(); :}
	;

storageEntries ::= /*empty*/
	{:  :}
	| storageEntries:ses storageEntry:se
	{:  :}
	;

storageEntry ::= dataDefinitionEntry:dde
	{:  :}
	| execSqlStatement:ess
	{:  :}
	;

execSqlStatement ::= ExecStatement:es
	{:  :}
	| ExecStatement:es SentenceEnd:se
	{:  :}
	;

localStorageSection ::= /*empty*/
	{:  :}
	| LocalStorageSectionHeader:lsh 
	{: my_parser.Builder.StartLocalStorageSection(lsh); :}
	storageEntries:ses	
	{: my_parser.Builder.EndLocalStorageSection(); :}
	;

dataDefinitionEntriesOpt ::= /*empty*/
	{:  :}
	| dataDefinitionEntries:ddes
	{:  :}
	;

dataDefinitionEntries ::= dataDefinitionEntry:dde
	{:  :}
	| dataDefinitionEntries:ddes dataDefinitionEntry:dde
	{:  :}
	;

dataDefinitionEntry ::=
	  DataDescriptionEntry:dde
	{: my_parser.Builder.StartDataDescriptionEntry(dde); :}
	| DataRedefinesEntry:dre
	{: my_parser.Builder.StartDataRedefinesEntry(dre); :}
	| DataRenamesEntry:dre
	{: my_parser.Builder.StartDataRenamesEntry(dre); :}
	| DataConditionEntry:dce
	{: my_parser.Builder.StartDataConditionEntry(dce); :}
	;

linkageSection ::= /*empty*/
	{:  :}
	| LinkageSectionHeader:lsh 
	{: my_parser.Builder.StartLinkageSection(lsh); :}
	dataDefinitionEntriesOpt:ddes
	{: my_parser.Builder.EndLinkageSection(); :}
	;

procedureDivisionOpt ::= /*empty*/
	{:  :}
	| procedureDivision:pdiv
	{:  :}
	;

// TCRFUN_DECLARATION_AS_NESTED_PROGRAM
procedureDivision ::=
	procedureDivisionHeader:pdh 	
	declarativesOpt:decls
	functionOrSectionDeclarations:elems
	{: my_parser.Builder.EndProcedureDivision(); :}
	;

procedureDivisionHeader ::= ProcedureDivisionHeader:pdh 
	{: my_parser.Builder.StartProcedureDivision(pdh); :}
	;

functionOrSectionDeclarations ::= /*empty*/
	{:  :}
	| functionOrSectionDeclarations:elems functionOrSectionDeclaration:elem
	{:  :}
	;

functionOrSectionDeclaration ::= functionDeclaration:fd
	{:  :}
	| section:s
	{:  :}
	;

// - custom header
// TCRFUN_DECLARATION_NO_IDENTIFICATION_DIVISION
// TCRFUN_DECLARATION_NO_ENVIRONMENT_DIVISION
// TCRFUN_MANDATORY_END_DECLARE
functionDeclaration ::=
	FunctionDeclarationHeader:fdh
	{: my_parser.Builder.StartFunctionDeclaration(fdh); :}
	dataDivisionOpt:dv
	functionProcedureDivisionOpt:fpd
	FunctionDeclarationEnd:fe
	{: my_parser.Builder.EndFunctionDeclaration(fe); :}
	;

functionProcedureDivisionOpt ::= /*empty*/
	{:  :}
	| functionProcedureDivision:fpd
	{:  :}
	;

// TCRFUN_DECLARATION_NO_DECLARATIVES
functionProcedureDivision ::=
	functionProcedureDivisionHeader:pdh 
	{: my_parser.Builder.EndFunctionProcedureDivision(); :}
| 	functionProcedureDivisionHeader:pdh 
	sections:alls
	{: my_parser.Builder.EndFunctionProcedureDivision(); :}
	;

functionProcedureDivisionHeader ::= ProcedureDivisionHeader:pdh 
	{: my_parser.Builder.StartFunctionProcedureDivision(pdh); :}
	;

declarativesOpt ::= /*empty*/
	{:  :}
	| declaratives:decls
	{:  :}
	;

declaratives ::=
	DeclarativesHeader:dh
	{: my_parser.Builder.StartDeclaratives(dh); :}
	declarativesSections:decls
	DeclarativesEnd:de
	{: my_parser.Builder.EndDeclaratives(de); :}
	;


declarativesSections ::= declarativesSection:ds
	{:  :}
	| declarativesSections:decls declarativesSection:ds
	{:  :}
	;

declarativesSection ::= 
	SectionHeader:sh 
	UseStatement:us
	{:  :}
	| SectionHeader:sh 
	UseStatement:us paragraphs:p
	{:  :}	
	;

sections ::= section:s
	{:  :}
	| sections:alls section:s
	{:  :}
	;

section ::= sectionHeader 
	{: my_parser.Builder.EndSection(); :}
	| sectionHeader paragraphs
	{: my_parser.Builder.EndSection(); :}
	| paragraphs
	{:  :}
	| sentences
	{:  :}
	;

sectionHeader ::= SectionHeader:sh 
	{: my_parser.Builder.StartSection(sh); :}
	;

paragraphHeader ::= ParagraphHeader:ph 
	{: my_parser.Builder.StartParagraph(ph); :}
	;

paragraphs ::= paragraph:p
	{:  :}
	| paragraphs:ps paragraph:p
	{:  :}
	;

paragraph ::= 
	paragraphHeader:ph 	
	{: my_parser.Builder.EndParagraph(); :}
	| paragraphHeader:ph sentences:alls
	{: my_parser.Builder.EndParagraph(); :}
	| sentences:alls
	{:  :}
	;

sentences ::= sentence:s
	{:  :}
	| sentences:alls sentence:s
	{:  :}
	;

sentence ::= SentenceEnd:send
	  {: my_parser.Builder.StartSentence(); my_parser.Builder.EndSentence(send); :}
    | statements:stmts SentenceEnd:send
	  {: my_parser.Builder.EndSentence(send, true); :}
	//JCM RESOLVE THIS TODO
	| ExecStatement:stmt
	{: my_parser.Builder.StartExecStatement(stmt); my_parser.Builder.EndExecStatement(); :}
	;

statements ::= statement:stmt
	{: my_parser.Builder.CheckStartSentenceLastStatement(); :}
	| statements:stmts statement:stmt
	{:  :}
	;

statement ::= singleStatement:stmt
	{:  :}
	| compoundStatement:stmt
	{:  :}
	| error statement /* ERROR Recovery on Statement ==> go to the next statement */
	{: :}
	;

singleStatement ::=
	ContinueStatement:stmt
	{: my_parser.Builder.OnContinueStatement(stmt); :}
	| EntryStatement:stmt
	{: my_parser.Builder.OnEntryStatement(stmt); :}
// -- arithmetic --
// -- see computeStatementConditional --
// -- data movement --
	| AcceptStatement:stmt // (DATE, DAY, DAY-OF-WEEK, TIME)
	{: my_parser.Builder.OnAcceptStatement(stmt); :}
	| InitializeStatement:stmt
	{: my_parser.Builder.OnInitializeStatement(stmt); :}
	| InspectStatement:stmt
	{: my_parser.Builder.OnInspectStatement(stmt); :}
	| MoveStatement:stmt
	{: my_parser.Builder.OnMoveStatement(stmt); :}
	| SetStatement:stmt
	{: my_parser.Builder.OnSetStatement(stmt); :}
// -- ending --
	| StopStatement:stmt
	{: my_parser.Builder.OnStopStatement(stmt); :}
	| ExitMethodStatement:stmt
	{: my_parser.Builder.OnExitMethodStatement(stmt); :}
	| ExitProgramStatement:stmt
	{: my_parser.Builder.OnExitProgramStatement(stmt); :}
	| GobackStatement:stmt
	{: my_parser.Builder.OnGobackStatement(stmt); :}
// -- input-output --
	| CloseStatement:stmt
	{: my_parser.Builder.OnCloseStatement(stmt); :}
	| DisplayStatement:stmt
	{: my_parser.Builder.OnDisplayStatement(stmt); :}
	| OpenStatement:stmt
	{: my_parser.Builder.OnOpenStatement(stmt); :}
// -- ordering --
	| MergeStatement:stmt
	{: my_parser.Builder.OnMergeStatement(stmt); :}
	| ReleaseStatement:stmt
	{: my_parser.Builder.OnReleaseStatement(stmt); :}
	| SortStatement:stmt
	{: my_parser.Builder.OnSortStatement(stmt); :}
// -- procedure-branching --
	| AlterStatement:stmt
	{: my_parser.Builder.OnAlterStatement(stmt); :}
	| ExitStatement:stmt
	{: my_parser.Builder.OnExitStatement(stmt); :}
	| GotoStatement:stmt
	{: my_parser.Builder.OnGotoStatement(stmt); :}
	| PerformProcedureStatement:stmt
	{: my_parser.Builder.OnPerformProcedureStatement(stmt); :}
// -- program or method linkage --// TYPECOBOL
	| ProcedureStyleCall:stmt
	{: my_parser.Builder.OnProcedureStyleCall(stmt, null); :}
	| ProcedureStyleCall:stmt CallStatementEnd:end
	{: my_parser.Builder.OnProcedureStyleCall(stmt, end); :}
	| CancelStatement:stmt
	{: my_parser.Builder.OnCancelStatement(stmt); :}
// -- DB2 & CICS integration --
	| ExecStatement:stmt
	{: my_parser.Builder.OnExecStatement(stmt); :}
	;
	
// Statements with optional body  
compoundStatement ::= addStatementConditional:stmt
		{:  :}
	|	callStatementConditional:stmt
		{:  :}
	|	computeStatementConditional:stmt
		{:  :}
	|	deleteStatementConditional:stmt
		{:  :}
	|	evaluateStatementWithBody:stmt
		{:  :}
	|	ifStatementWithBody:stmt
		{:  :}
	|	invokeStatementConditional:stmt
		{:  :}
	|	divideStatementConditional:stmt
		{:  :}
	|	multiplyStatementConditional:stmt
		{:  :}
	|	performStatementWithBody:stmt
		{:  :}
	|	readStatementConditional:stmt
		{:  :}
	|	returnStatementConditional:stmt
		{:  :}
	|	rewriteStatementConditional:stmt
		{:  :}
	|	searchStatementWithBody:stmt
		{:  :}
	|	startStatementConditional:stmt
		{:  :}
	|	stringStatementConditional:stmt
		{:  :}
	|	subtractStatementConditional:stmt
		{:  :}
	|	unstringStatementConditional:stmt
		{:  :}
	|	writeStatementConditional:stmt
		{:  :}
	|	xmlGenerateStatementConditional:stmt
		{:  :}
	|	xmlParseStatementConditional:stmt
		{:  :}
	;

addStatementConditional ::=
		addStatement
		{: my_parser.Builder.EndAddStatementConditional(); :}
	|	addStatement AddStatementEnd:end
		{: my_parser.Builder.EndAddStatementConditional(end); :}
	|	addStatement sizeErrorConditions:conds
		{:  my_parser.Builder.EndAddStatementConditional(); :}
	|	addStatement sizeErrorConditions:conds AddStatementEnd:end
		{:  my_parser.Builder.EndAddStatementConditional(end); :}
	;

addStatement ::= AddStatement:stmt
	{: my_parser.Builder.StartAddStatementConditional(stmt); :}
	;

callStatementConditional ::=
		callStatement
		{: my_parser.Builder.EndCallStatementConditional(); :}
	|	callStatement CallStatementEnd:end
		{: my_parser.Builder.EndCallStatementConditional(end); :}
	|	callStatement callStatementConditions:conds
		{: my_parser.Builder.EndCallStatementConditional(); :}
	|	callStatement callStatementConditions:conds CallStatementEnd:end
		{:  my_parser.Builder.EndCallStatementConditional(end); :}
	;

callStatement ::= CallStatement:stmt
	{: my_parser.Builder.StartCallStatementConditional(stmt); :}
	;

callStatementConditions ::=
	  onException:on
	{:  :}
	| noException:not_on
	{:  :}
	| onOverflow:on
	{:  :}
	;

computeStatementConditional ::=
		computeStatement
		{: my_parser.Builder.EndComputeStatementConditional(); :}
	|	computeStatement ComputeStatementEnd:end
		{: my_parser.Builder.EndComputeStatementConditional(end); :}
	|	computeStatement sizeErrorConditions:conds
		{: my_parser.Builder.EndComputeStatementConditional(); :}
	|	computeStatement sizeErrorConditions:conds ComputeStatementEnd:end
		{: my_parser.Builder.EndComputeStatementConditional(end); :}
	;

computeStatement ::= ComputeStatement:stmt
	{: my_parser.Builder.StartComputeStatementConditional(stmt); :}
	;

deleteStatementConditional ::=
		deleteStatement
		{: my_parser.Builder.EndDeleteStatementConditional(); :}
	|	deleteStatement DeleteStatementEnd:end
		{: my_parser.Builder.EndDeleteStatementConditional(end); :}
	|	deleteStatement keyConditions:conds
		{: my_parser.Builder.EndDeleteStatementConditional(); :}
	|	deleteStatement keyConditions:conds DeleteStatementEnd:end
		{: my_parser.Builder.EndDeleteStatementConditional(end); :}
	;

deleteStatement ::= DeleteStatement:stmt
	{: my_parser.Builder.StartDeleteStatementConditional(stmt); :}
	;


divideStatementConditional ::=
		divideStatement
		{: my_parser.Builder.EndDivideStatementConditional(); :}
	|	divideStatement DivideStatementEnd:end
		{: my_parser.Builder.EndDivideStatementConditional(end); :}
	|	divideStatement sizeErrorConditions:conds
		{: my_parser.Builder.EndDivideStatementConditional(); :}
	|	divideStatement sizeErrorConditions:conds DivideStatementEnd:end
		{: my_parser.Builder.EndDivideStatementConditional(end); :}
	;

divideStatement ::= DivideStatement:stmt
	{: my_parser.Builder.StartDivideStatementConditional(stmt); :}
	;

evaluateStatementWithBody ::=
		evaluateStatement
		{: my_parser.Builder.EndEvaluateStatementWithBody(); :}
	|	evaluateStatement EvaluateStatementEnd:ese
		{: my_parser.Builder.EndEvaluateStatementWithBody(ese); :}
	|	evaluateStatement whenConditionClauses:wccs
		{: my_parser.Builder.EndEvaluateStatementWithBody(); :}
	|	evaluateStatement whenConditionClauses:wccs  EvaluateStatementEnd:ese
		{: my_parser.Builder.EndEvaluateStatementWithBody(ese); :}
	|	evaluateStatement whenOtherClause:woc
		{: my_parser.Builder.EndEvaluateStatementWithBody(); :}
	|	evaluateStatement whenOtherClause:woc EvaluateStatementEnd:ese
		{: my_parser.Builder.EndEvaluateStatementWithBody(ese); :}
	|	evaluateStatement whenConditionClauses:wccs whenOtherClause:woc
		{: my_parser.Builder.EndEvaluateStatementWithBody(); :}
	|	evaluateStatement whenConditionClauses:wccs whenOtherClause:woc EvaluateStatementEnd:ese
		{: my_parser.Builder.EndEvaluateStatementWithBody(ese); :}
	;

evaluateStatement ::= EvaluateStatement:est
	{: my_parser.Builder.StartEvaluateStatementWithBody(est); :}
	;

whenConditionClauses ::= 
		whenConditionClause:wcc
		{:  :}
	|	whenConditionClauses:wccs whenConditionClause:wcc
		{:  :}
	;

whenConditionClause ::= whenEvaluateConditionsStart:wecs  statements:stmts
	{: my_parser.Builder.EndWhenConditionClause(); :}
	;

whenEvaluateCondition ::= WhenSearchCondition:wec
	{: RESULT = wec; :}
	| WhenCondition:wec
	{: RESULT = wec; :}
	;

whenEvaluateConditions ::= whenEvaluateCondition:wec
	{: RESULT = new CodeElementList(){wec}; :}
	| whenEvaluateConditions:wecs whenEvaluateCondition:wec
	{: wecs.Add(wec); RESULT = wecs; :}
	;

whenEvaluateConditionsStart ::= whenEvaluateConditions:wecs
	{: my_parser.Builder.StartWhenConditionClause(wecs); :}
	;


whenOtherClause ::= whenOtherCondition:woc statements:stmts
	{: my_parser.Builder.EndWhenOtherClause(); :}
	;

whenOtherCondition ::= WhenOtherCondition:woc 
	{: my_parser.Builder.StartWhenOtherClause(woc); :}
	;

ifStatementWithBody ::=
	ifstatement:ifs statements:thenStmts
	{: my_parser.Builder.EndIfStatementWithBody(); :}
	| ifstatement:ifs statements:thenStmts IfStatementEnd:end
	{: my_parser.Builder.EndIfStatementWithBody(end); :}

	| ifstatement:ifs nextSentenceStatement:ness
	{:  my_parser.Builder.EndIfStatementWithBody(); :}
	| ifstatement:ifs nextSentenceStatement:ness IfStatementEnd:end
	{: my_parser.Builder.EndIfStatementWithBody(end); :}

	| ifstatement:ifs statements:thenStmts elseCondition:ec statements:elseStmts
	{: my_parser.Builder.EndIfStatementWithBody(); :}
	| ifstatement:ifs statements:thenStmts elseCondition:ec nextSentenceStatement:ness
	{: my_parser.Builder.EndIfStatementWithBody(); :}

	| ifstatement:ifs statements:thenStmts elseCondition:ec statements:elseStmts IfStatementEnd:end
	{: my_parser.Builder.EndIfStatementWithBody(end); :}
	| ifstatement:ifs statements:thenStmts elseCondition:ec nextSentenceStatement:ness IfStatementEnd:end
	{: my_parser.Builder.EndIfStatementWithBody(end); :}

	| ifstatement:ifs nextSentenceStatement:ness elseCondition:ec statements:elseStmts
	{: my_parser.Builder.EndIfStatementWithBody(); :}
	| ifstatement:ifs nextSentenceStatement:nessThen elseCondition:ec nextSentenceStatement:nessElse
	{: my_parser.Builder.EndIfStatementWithBody(); :}

	| ifstatement:ifs nextSentenceStatement:ness elseCondition:ec statements:elseStmts IfStatementEnd:end
	{: my_parser.Builder.EndIfStatementWithBody(end); :}
	| ifstatement:ifs nextSentenceStatement:nessThen elseCondition:ec nextSentenceStatement:nessElse IfStatementEnd:end
	{: my_parser.Builder.EndIfStatementWithBody(end); :}
	;

ifstatement ::= IfStatement:ifs
	{: my_parser.Builder.StartIfStatementWithBody(ifs); :}
	;

elseCondition ::= ElseCondition:ec 
	{: my_parser.Builder.EnterElseClause(ec); :}
	;

nextSentenceStatement ::= NextSentenceStatement:next
	{: my_parser.Builder.AddNextSentenceStatement(next); :}
	;

invokeStatementConditional ::=
		invokeStatement:stmt
		{: my_parser.Builder.EndInvokeStatementConditional(); :}
	|	invokeStatement:stmt InvokeStatementEnd:end
		{: my_parser.Builder.EndInvokeStatementConditional(end); :}
	|	invokeStatement:stmt exceptionConditions:conds
		{: my_parser.Builder.EndInvokeStatementConditional(); :}
	|	invokeStatement:stmt exceptionConditions:conds InvokeStatementEnd:end
		{: my_parser.Builder.EndInvokeStatementConditional(end); :}
	;

invokeStatement ::= InvokeStatement:stmt
	{: my_parser.Builder.StartInvokeStatementConditional(stmt); :}
	;

multiplyStatementConditional ::=
		multiplyStatement:stmt
		{: my_parser.Builder.EndMultiplyStatementConditional(); :}
	|	multiplyStatement:stmt MultiplyStatementEnd:end
		{: my_parser.Builder.EndMultiplyStatementConditional(end); :}
	|	multiplyStatement:stmt sizeErrorConditions:conds
		{: my_parser.Builder.EndMultiplyStatementConditional(); :}
	|	multiplyStatement:stmt sizeErrorConditions:conds MultiplyStatementEnd:end
		{: my_parser.Builder.EndMultiplyStatementConditional(end); :}
	;

multiplyStatement ::= MultiplyStatement:stmt
	{: my_parser.Builder.StartMultiplyStatementConditional(stmt); :}
	;

performStatementWithBody ::=			
		performStatement:stmt
		{: my_parser.Builder.EndPerformStatementWithBody(); :}
	|	performStatement:stmt PerformStatementEnd:end
		{: my_parser.Builder.EndPerformStatementWithBody(end); :}
	|	performStatement:stmt statements:stmts
		{: my_parser.Builder.EndPerformStatementWithBody(); :}
	|	performStatement:stmt statements:stmts PerformStatementEnd:end
		{: my_parser.Builder.EndPerformStatementWithBody(end); :}
	;

performStatement ::= PerformStatement:stmt
	{: my_parser.Builder.StartPerformStatementWithBody(stmt); :}
	;

readStatementConditional ::=
		readStatement:stmt
		{: my_parser.Builder.EndReadStatementConditional(); :}
	|	readStatement:stmt ReadStatementEnd:end
		{: my_parser.Builder.EndReadStatementConditional(end); :}
	|	readStatement:stmt rwStatementConditions:conds
		{: my_parser.Builder.EndReadStatementConditional(); :}
	|	readStatement:stmt rwStatementConditions:conds ReadStatementEnd:end
		{: my_parser.Builder.EndReadStatementConditional(end); :}
	;

readStatement ::= ReadStatement:stmt
	{: my_parser.Builder.EnterReadStatementConditional(stmt); :}
	;

rwStatementCondition ::=
	  onAtEnd:at
	{:  :}
	| noAtEnd:not_at
	{:  :}
	| onInvalidKey:on
	{:  :}
	| noInvalidKey:not_on
	{:  :}
	;

rwStatementConditions ::=
		rwStatementCondition:rwsc
		{:  :}
	|	rwStatementConditions:rwscs rwStatementCondition:rwsc
		{:  :}
	;

returnStatementConditional ::=
		returnStatement:stmt
		{: my_parser.Builder.EndReturnStatementConditional(); :}
	|	returnStatement:stmt ReturnStatementEnd:end
		{: my_parser.Builder.EndReturnStatementConditional(end); :}
	|	returnStatement:stmt endConditions:conds
		{: my_parser.Builder.EndReturnStatementConditional(); :}
	|	returnStatement:stmt endConditions:conds ReturnStatementEnd:end
		{: my_parser.Builder.EndReturnStatementConditional(end); :}
	;

returnStatement ::= ReturnStatement:stmt
	{: my_parser.Builder.EnterReturnStatementConditional(stmt); :}
	;

rewriteStatementConditional ::=
		rewriteStatement:stmt
		{: my_parser.Builder.EndRewriteStatementConditional(); :}
	|	rewriteStatement:stmt RewriteStatementEnd:end
		{: my_parser.Builder.EndRewriteStatementConditional(end); :}
	|	rewriteStatement:stmt keyConditions:conds
		{: my_parser.Builder.EndRewriteStatementConditional(); :}
	|	rewriteStatement:stmt keyConditions:conds RewriteStatementEnd:end
		{: my_parser.Builder.EndRewriteStatementConditional(end); :}
	;

rewriteStatement ::= RewriteStatement:stmt
	{: my_parser.Builder.StartRewriteStatementConditional(stmt); :}
	;

searchStatementWithBody ::=
		searchStatement:stmt whenSearchConditionClauses:wsccs
		{: my_parser.Builder.EndSearchStatementWithBody(); :}
	|	searchStatement:stmt whenSearchConditionClauses:wsccs SearchStatementEnd:end
		{: my_parser.Builder.EndSearchStatementWithBody(end); :}
	|	searchStatement:stmt onAtEnd:cend whenSearchConditionClauses:wsccs
		{: my_parser.Builder.EndSearchStatementWithBody(); :}
	|	searchStatement:stmt onAtEnd:cend whenSearchConditionClauses:wsccs SearchStatementEnd:end
		{: my_parser.Builder.EndSearchStatementWithBody(end); :}
	;

searchStatement ::= SearchStatement:stmt
	{: my_parser.Builder.StartSearchStatementWithBody(stmt); :}
	;

whenSearchConditionClause ::= 
		whenSearchCondition:wsc  statements:stmts
		{: my_parser.Builder.EndWhenSearchConditionClause(); :}
	|	whenSearchCondition:wsc  nextSentenceStatement:ness
		{: my_parser.Builder.EndWhenSearchConditionClause(); :}
	;

whenSearchCondition ::= WhenSearchCondition:wsc 
	{: my_parser.Builder.StartWhenSearchConditionClause(wsc); :}
	;

whenSearchConditionClauses ::= whenSearchConditionClause:wscc
		{:  :}
	|	whenSearchConditionClauses:wsccs whenSearchConditionClause:wscc
		{:  :}
	;

startStatementConditional ::=
		startStatement:stmt
		{: my_parser.Builder.EndStartStatementConditional(); :}
	|	startStatement:stmt StartStatementEnd:end
		{: my_parser.Builder.EndStartStatementConditional(end); :}
	|	startStatement:stmt keyConditions:conds
		{: my_parser.Builder.EndStartStatementConditional(); :}
	|	startStatement:stmt keyConditions:conds StartStatementEnd:end
		{: my_parser.Builder.EndStartStatementConditional(end); :}
	;

startStatement ::= StartStatement:stmt
	{: my_parser.Builder.StartStartStatementConditional(stmt); :}
	;

stringStatementConditional ::=
		stringStatement:stmt
		{: my_parser.Builder.EndStringStatementConditional(); :}
	|	stringStatement:stmt StringStatementEnd:end
		{: my_parser.Builder.EndStringStatementConditional(end); :}
	|	stringStatement:stmt overflowConditions:conds
		{: my_parser.Builder.EndStringStatementConditional(); :}
	|	stringStatement:stmt overflowConditions:conds StringStatementEnd:end
		{: my_parser.Builder.EndStringStatementConditional(end); :}
	;

stringStatement ::= StringStatement:stmt
	 {: my_parser.Builder.StartStringStatementConditional(stmt); :}
	 ;

subtractStatementConditional ::=
		subtractStatement:stmt
		{: my_parser.Builder.EndSubtractStatementConditional(); :}
	|	subtractStatement:stmt SubtractStatementEnd:end
		{: my_parser.Builder.EndSubtractStatementConditional(end); :}
	|	subtractStatement:stmt sizeErrorConditions:conds
		{: my_parser.Builder.EndSubtractStatementConditional(); :}
	|	subtractStatement:stmt sizeErrorConditions:conds SubtractStatementEnd:end
		{: my_parser.Builder.EndSubtractStatementConditional(end); :}
	;

subtractStatement ::= SubtractStatement:stmt
	{: my_parser.Builder.StartSubtractStatementConditional(stmt); :}
	;

unstringStatementConditional ::=
		unstringStatement:stmt
		{: my_parser.Builder.EndUnstringStatementConditional(); :}
	|	unstringStatement:stmt UnstringStatementEnd:end
		{: my_parser.Builder.EndUnstringStatementConditional(end); :}
	|	unstringStatement:stmt overflowConditions:conds
		{: my_parser.Builder.EndUnstringStatementConditional(); :}
	|	unstringStatement:stmt overflowConditions:conds UnstringStatementEnd:end
		{: my_parser.Builder.EndUnstringStatementConditional(end); :}
	;

unstringStatement ::= UnstringStatement:stmt
	{: my_parser.Builder.StartUnstringStatementConditional(stmt); :}
	;

writeStatementConditional ::=
		writeStatement:stmt
		{: my_parser.Builder.EndWriteStatementConditional(); :}
	|	writeStatement:stmt WriteStatementEnd:end
		{: my_parser.Builder.EndWriteStatementConditional(end); :}
	|	writeStatement:stmt rwStatementConditions:conds
		{: my_parser.Builder.EndWriteStatementConditional(); :}
	|	writeStatement:stmt rwStatementConditions:conds WriteStatementEnd:end
		{: my_parser.Builder.EndWriteStatementConditional(end); :}
	;

writeStatement ::= WriteStatement:stmt
	{: my_parser.Builder.StartWriteStatementConditional(stmt); :}
	;

xmlGenerateStatementConditional ::=
		xmlGenerateStatement:stmt
		{: my_parser.Builder.EndXmlGenerateStatementConditional(); :}
	|	xmlGenerateStatement:stmt XmlStatementEnd:end
		{: my_parser.Builder.EndXmlGenerateStatementConditional(end); :}
	|	xmlGenerateStatement:stmt exceptionConditions:conds
		{: my_parser.Builder.EndXmlGenerateStatementConditional(); :}
	|	xmlGenerateStatement:stmt exceptionConditions:conds XmlStatementEnd:end
		{: my_parser.Builder.EndXmlGenerateStatementConditional(end); :}
	;

xmlGenerateStatement ::= XmlGenerateStatement:stmt
	{: my_parser.Builder.StartXmlGenerateStatementConditional(stmt); :}
	;

xmlParseStatementConditional ::=
		xmlParseStatement:stmt
		{: my_parser.Builder.EndXmlParseStatementConditional(); :}
	|	xmlParseStatement:stmt XmlStatementEnd:end
		{: my_parser.Builder.EndXmlParseStatementConditional(end); :}
	|	xmlParseStatement:stmt exceptionConditions:conds
		{: my_parser.Builder.EndXmlParseStatementConditional(); :}
	|	xmlParseStatement:stmt exceptionConditions:conds XmlStatementEnd:end
		{: my_parser.Builder.EndXmlParseStatementConditional(end); :}
	;

xmlParseStatement ::= XmlParseStatement:stmt
	{: my_parser.Builder.StartXmlParseStatementConditional(stmt); :}
	;

// Conditional execution of statements

onAtEnd ::= atEndCondition:cond statements:stmts
	{: my_parser.Builder.EndOnAtEnd(); :}
	;

atEndCondition ::= AtEndCondition:cond 
	{: my_parser.Builder.StartOnAtEnd(cond); :}
	;

noAtEnd ::= notAtEndCondition:cond statements:stmts
	{: my_parser.Builder.EndNoAtEnd(); :}
	;

notAtEndCondition ::= NotAtEndCondition:cond 
	{: my_parser.Builder.StartNoAtEnd(cond); :}
	;

endConditions ::= onAtEnd:at
	{:  :}
	| noAtEnd:no_at
	{:  :}
	| endConditions:econds onAtEnd:at
	{:  :}
	| endConditions:econds noAtEnd:no_at
	{:  :}
	;

onException ::= onExceptionCondition:cond statements:stmts
	{: my_parser.Builder.EndOnException(); :}
	;

onExceptionCondition ::= OnExceptionCondition:cond 
	{: my_parser.Builder.StartOnException(cond); :}
	;

noException ::= notOnExceptionCondition:cond statements:stmts
	{: my_parser.Builder.EndNoException(); :}
	;

notOnExceptionCondition ::= NotOnExceptionCondition:cond 
	{: my_parser.Builder.StartNoException(cond); :}
	;

exceptionConditions ::= onException:on
	{:  :}
	| noException:not_on
	{:  :}
	| exceptionConditions:econds onException:on
	{:  :}
	| exceptionConditions:econds noException:not_on
	{:  :}
	;


onInvalidKey ::= invalidKeyCondition:cond statements:stmts
	{: my_parser.Builder.EndOnInvalidKey(); :}
	;

invalidKeyCondition ::= InvalidKeyCondition:cond 
	{: my_parser.Builder.StartOnInvalidKey(cond); :}
	;

noInvalidKey ::= notInvalidKeyCondition:cond statements:stmts
	{: my_parser.Builder.EndNoInvalidKey(); :}
	;

notInvalidKeyCondition ::= NotInvalidKeyCondition:cond 
	{: my_parser.Builder.StartNoInvalidKey(cond); :}
	;

keyConditions ::= onInvalidKey:invalid
	{:  :}
	| noInvalidKey:not_invalid
	{:  :}
	| keyConditions:kconds onInvalidKey:valid
	{:  :}
	| keyConditions:kconds noInvalidKey:not_invalid
	{:  :}
	;

onOverflow ::= onOverflowCondition:cond statements:stmts
	{: my_parser.Builder.EndOnOverflow(); :}
	;
onOverflowCondition ::= OnOverflowCondition:cond 
	{: my_parser.Builder.StartOnOverflow(cond); :}
	;

noOverflow ::= notOnOverflowCondition:cond statements:stmts
	{: my_parser.Builder.EndNoOverflow(); :}
	;

notOnOverflowCondition ::= NotOnOverflowCondition:cond 
	{: my_parser.Builder.StartNoOverflow(cond); :}
	;

overflowConditions ::= onOverflow:on
	{:  :}
	| noOverflow:not_on
	{:  :}
	| overflowConditions:oconds onOverflow:on
	{:  :}
	| overflowConditions:oconds noOverflow:not_on
	{:  :}
	;

onSizeError ::= onSizeErrorCondition:cond statements:stmts
	{:  my_parser.Builder.EndOnSizeError(); :}
	;
onSizeErrorCondition ::= OnSizeErrorCondition:cond 
	{: my_parser.Builder.StartOnSizeError(cond); :}
	;

noSizeError ::= notOnSizeErrorCondition:cond statements:stmts
	{:  my_parser.Builder.EndNoSizeError(); :}
	;

notOnSizeErrorCondition ::= NotOnSizeErrorCondition:cond 
	{: my_parser.Builder.StartNoSizeError(cond); :}
	;

sizeErrorConditions ::= 
	  onSizeError:on
		{: :}
	| noSizeError:not_on
		{: :}
	| sizeErrorConditions:seconds onSizeError:on
		{: :}
	| sizeErrorConditions:seconds noSizeError:not_on
		{: :}
	;
